---
booktitle: Proceedings of The 8th Asian Conference on Machine Learning
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
volume: 63
year: '2016'
shortname: ACML
published: 2016-11-20
start: 2016-11-16
end: 2016-11-18
sections:
- name: preface
  title: Front Matter
- name: default
  title: Accepted Papers
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: acml2016
month: 0
cycles: false
editor:
- given: Robert J.
  family: Durrant
- given: Kee-Eung
  family: Kim
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 8th Asian Conference on Machine Learning
    Held in The University of Waikato, Hamilton, New Zealand on 16-18 November 2016

  Published as Volume 63 by the Proceedings of Machine Learning Research on 20 November 2016.

  Volume Edited by:
    Robert J. Durrant
    Kee-Eung Kim

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 16--18 Nov
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v63"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v63
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Asian Conference on Machine Learning
  url: http://www.acml-conf.org/2016/
  location: The University of Waikato, Hamilton, New Zealand
  dates:
  - 2016-11-16
  - 2016-11-17
  - 2016-11-18
  number: 8
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
